### ISSUE TITLE
Center contents with CSS

### ISSUE THREAD

**Issue by climaxmba** [sundaymark/Etch-a-Sketch#1]
Centering the contents would make the site look nicer.

![image](https://user-images.githubusercontent.com/106796090/220708218-baea2d94-be00-42ba-8f4e-9e3c07a4e8fa.png)

Put these to your style in order to center it:
```css
body {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.heading {
    background-color: rgb(37, 54, 54);
    color: rgb(205, 234, 235);
    text-align: center;
    width: -webkit-fill-available;
}
```
And also add some margin and padding.
